'''
Definir una función inversa() que calcule la inversión de una cadena. Por ejemplo la
cadena "estoy probando" debería devolver la cadena "odnaborp yotse"
'''

def inversa(cadena):
    reves=""
    for i in cadena:
        reves=i+reves
    return print(reves)
inversa("HOLA")

'''
SI LA PALABRA ES HOLA
i RECORRE LA CADENA 
Y REVES INICIALMENTE NO TIENE NADA

PRIMERA ITERACION DEL CICLO FOR
    i SE ENCUENTRA CON EL PRIMER CARACTER DE LA CADENA QUE ES H
    SE ALMACENA EN REVES DANDO COMO RESULTADO H
    REVES=H
SEGUNDA ITERACION DEL CICLO FOR
    i SE ENCUENTRA CON EL CARACTER O
    SE REALIZA LA SUMA DE REVES ES DECIR i=O Y REVES H DANDO COMO RESULTADO
    REVES = OH
 TERCERA ITERACION DEL CICLO FOR
    i SE ENCUTRA CON L
    SE REALIZA LA SUMA DE REVES: i= L + RREVES=OH RESULTANDO
    REVES=LOH
CUARTA ITERACION DEL CICLO FOR
    i SE ENCUENTRA CON A
    SE REALIZA LA SUMA DE REVES: i=A + REVES=LOH RESULTANDO EN
    REVES=ALOH    
    
LO QUE QUIERE DECIR QUE: LO QUE DICTA LA ORIENTACION DE LA PALABLA 
ES LA POSICION DE i EN LA SUMA DE REVES
'''